model_reasoning_summary = "concise" 
model_verbosity = "low"
sandbox_mode = "danger-full-access"
model = "gpt-5.3-codex"
model_reasoning_effort = "high"
personality = "pragmatic"
web_search = "live"

[features]
rmcp_client = true

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"
