model_reasoning_summary = "concise" 
model_verbosity = "low"
sandbox_mode = "danger-full-access"
model = "gpt-5.2-codex"
model_reasoning_effort = "high"
personality = "pragmatic"

[tools]
web_search = true
